version: "3"
services:
  user_service:
    build: ./
    container_name: User_service_prod
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    command: npm run start